def exclude_term():
    exclude_term = ["craigslist.", "careerboard.com", "simplyhired.com", "sidehustlehq.com", "owler.com", "jobinventory.com",'yellowpages.', 'huffingtonpost.com', 'yahoo.com', 'ezlocal.com', 'superpages.com', 'capterra.com',
                    'angieslist.com', 'thomasnet.com', 'indeed.com', 'amazon.com', 'bloomberg.com', 'ziprecruiter.com',
                    'monster.com', 'manta.com', 'bbb.org', 'facebook.com', 'yelp.com', 'cognate.com', 'yellowpages.com',
                    'linkedin.com', 'angieslist.com', '.gov', 'zoominfo.com', 'bloomberg.com', 'superpage.com',
                    'bluebook.com', 'opencorporate.com', 'bizstanding.com', 'indeed.com', 'homeadvisor', 'bizapedia',
                    'thumbtack', 'findthecompany', 'nasdaq', 'smallbusinessdb', 'whitepages', 'caselaw', 'bizpedia',
                    'plus.google', 'prezi.com', '.co.', 'kompass', 'usplaces.com', 'buzzfile.com', 'businessdetail',
                    'companydetail', 'hipaaspace', 'registry', 'twitter', 'govtribe', 'foursquare',
                    'referenceforbusiness', '.edu', '.uk', 'ebay.', 'corps', 'amazon.', 'youtube.', 'statelaw',
                    'buildzoom', 'company-detail', 'corporationwiki', 'moreopp', 'freightconnect', 'care.com', 'scribd',
                    'groupon', 'estatesales', 'carmax', 'alibaba', 'porch.com', 'yellowbook', 'usbizs', 'thomasnet',
                    'houzz', 'www.inc.com', 'foodcorporations', 'encyclopedia.com', 'directionus.com',
                    'companiesflorida', 'landscape', '.com.', 'staffing', 'allonesearch', 'broker', 'localbiziness',
                    'law.justia', 'investment', 'investor', 'google.', 'roofing', 'international', 'carpet',
                    'construction', 'wealth', 'insurance', 'auto', 'grading', 'health', 'siccode', 'kompass',
                    'macraesbluebook', 'indeed', 'bakery', 'whitepages', 'staff', 'hoovers', 'news', 'crunchbase',
                    'myvisajob', 'furniture', 'cpa', 'wiki', 'jewel', 'journal', 'pinterest', 'twitter', 'dealer',
                    'porch', 'investor', 'registry', 'farm', 'wedding', 'industrycat', 'wordpress', 'obituar',
                    'overstock', 'aerospace', 'usacorporates', 'instagram', '.mil', 'kayak.com', 'intelius', '.in/',
                    'dictionary', 'cortera', 'payscale', 'uscompanies', 'mapquest', 'glassdoor', 'weebly',
                    'businessfinder', 'macafee', 'espn.com', 'chron.com', 'imdb.com', 'food', 'lawyer',
                    'corporationsearchus.com', 'tribune', 'ancestry.com', 'nytimes.com', 'wsj.com', 'bostonglobe.com',
                    'careerbuilder.com', 'glassdoor.com', 'snagajob.com', 'dice.com', 'beyond.com', 'flexjobs.com']
    exclude_term2 = [".edu", ".gov", ".in/", ".mil", ".uk", "aerospace.com", "alibaba.com", "allonesearch",
                     "amazon.com", "ancestry.com", "angieslist.com", "aphis.usda.gov", "auto.com", "bbb.org",
                     "beyond.com", "bizapedia.com", "bizquest.com", "bizstanding.com", "bloomberg.com",
                     "bostonglobe.com", "bplans.com", "broker", "buildzoom.com", "businessdetail.com",
                     "businessfinder.com", "buzzfile.com", "capterra.com", "care.com", "careerbuilder.com",
                     "carmax.com", "caselaw.com", "chron.com", "cognate.com", "companiesflorida.com",
                     "company-detail.com", "companydetail.com", "corporationsearchus.com", "corporationwiki.com",
                     "cortera.com", "crunchbase.com", "dexknows.com", "dice.com", "dictionary.com", "directionus.com",
                     "ebay.com", "encyclopedia.com", "espn.com", "facebook.com", "findthecompany", "finduslocal.com",
                     "flexjobs.com", "foursquare.com", "freightconnect.com", "glassdoor.com", "google.com",
                     "govtribe.com", "grainger.com", "groupon.com", "health.com", "hipaaspace.com", "homeadvisor.com",
                     "hoovers.com", "houzz.com", "hub.biz", "imdb.com", "indeed.com", "industrycat.com",
                     "instagram.com", "intelius.com", "investors.com", "jobaps.com", "jobs.oodle.com", "jobs.yakaz.com",
                     "jobs2careers.com", "kayak.com", "kompass.com", "law.justia.com", "lawyer.com", "linkedin.com",
                     "listings.findthecompany.com", "local.com", "local.yahoo.com", "localbiziness.com",
                     "macraesbluebook.com", "maidpro.com", "manta.com", "mapquest.com", "monster.com", "moreopp.com",
                     "myvisajob.com", "nasdaq.com", "bbc.com", "nytimes.com", "msn.com", "opencorporate.com",
                     "overstock.com", "payscale.com", "pinterest.com", "plus.google", "porch", "porch.com", "prezi.com",
                     "referenceforbusiness.com", "scribd.com", "search.yahoo.com", "siccode.com", "smallbusinessdb.com",
                     "snagajob.com", "statelaw.com", "superpages.com", "thomasnet.com", "thumbtack.com", "tribune.com",
                     "twitter.com", "usacareerdb.com", "usacorporates.com", "usatoday.com", "usbizs.com",
                     "uscompanies.com", "usplaces.com", ".wedding", "weebly.com", "whitepages.com", "wiki.com",
                     "wordpress.com", "wsj.com", "www.inc.com", "www1.looksmart.com", "yellowpages.com",
                     "yellowpagesgoesgreen.org", "yelp.com", "youtube.com", "ziprecruiter.com", "zoominfo.com",
                     "usnews.com"]
    return list(set(exclude_term) | set(exclude_term2))
