# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingScraper', '0003_auto_20170620_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
