# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=15)),
                ('file_length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('zipcode', models.TextField(blank=True, max_length=10)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('owner_Name', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadListLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=25)),
                ('upload_type', models.CharField(max_length=10)),
                ('file_length', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('name', 'url')]),
        ),
    ]
