# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('googleScraper', '0002_auto_20170727_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='datetime',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
